name: Test iOS SDK
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
      - release/**
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: testing ... iPhone 14
        run: >-
          xcodebuild test -workspace fattmerchant-ios-sdk.xcworkspace -scheme FattmerchantTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
      - name: testing ... iPad Pro 12.9
        run: >-
          xcodebuild test -workspace fattmerchant-ios-sdk.xcworkspace -scheme FattmerchantTests -destination 'platform=iOS Simulator,OS=16.0,name=iPad Pro (12.9-inch) (5th generation)'
