name: Test iOS SDK
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
      - release/**
jobs:
  build-ios:
    name: Compile on iOS 16.0
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build SDK for iOS 16.0
        run: xcodebuild -workspace fattmerchant-ios-sdk.xcworkspace -scheme fattmerchant-ios-sdk -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
  unit-test:
    name: Run Tests on iOS 16.0
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: xcodebuild test -workspace fattmerchant-ios-sdk.xcworkspace -scheme FattmerchantTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'